sphinx-contrib/spelling

sphinxcontrib/spelling/builder.py
Requires https://github.com/sphinx-doc/sphinx/pull/4110 to work
=> Fixes #1 -- disable smart quotes so that we can recognize contractions/posessives correctly

docs/source/customize.rst, docs/source/developers.rst, sphinxcontrib/spelling/builder.py, sphinxcontrib/spelling/tests/test_builder.py
=> Make it possible to use several user-provided dictionary files

.travis.yml, setup.cfg, tox.ini
=> fix python_requires

tox.ini
=> update pkglint to check wheels too

.travis.yml, sphinxcontrib/spelling/tests/test_builder.py, sphinxcontrib/spelling/tests/test_checker.py, sphinxcontrib/spelling/tests/test_filter.py
=> fix linter errors

.travis.yml, docs/source/conf.py, docs/source/customize.rst, docs/source/developers.rst, docs/source/history.rst, docs/source/index.rst, docs/source/install.rst, docs/source/spelling_people.txt, docs/source/spelling_wordlist.txt, releasenotes/notes/entry-point-b2ad290cd46d055c.yaml, releasenotes/notes/optional-pyenchant-76a049d1d6104cfb.yaml, releasenotes/notes/parallel-builds-ea64713dd82a4498.yaml, requirements.txt, setup.cfg, sphinxcontrib/spelling/__init__.py, sphinxcontrib/spelling/asset.py, sphinxcontrib/spelling/builder.py, sphinxcontrib/spelling/checker.py, sphinxcontrib/spelling/directive.py, sphinxcontrib/spelling/tests/test_builder.py, tox.ini
=> support parallel builds

.travis.yml, docs/source/run.rst, sphinxcontrib/spelling/builder.py, sphinxcontrib/spelling/tests/test_builder.py, tox.ini
=> only create output files when writing warnings

docs/source/spelling_people.txt, releasenotes/notes/exclude-patterns-83910a7f02407597.yaml
=> add release note for spelling_exclude_patterns configuration option

tox.ini
Out of date since 1004925eb8f9ebbcd0b18445305370f5bfe0b3b7.
=> Remove outdated comment in tox.ini about "fix-py3-install"

setup.cfg
For a complete list of available trove classifiers, see:
https://pypi.org/classifiers/
=> Add 'Framework :: Sphinx :: Extension' trove classifier

sphinxcontrib/spelling/filters.py
Simplify with the newer Python 3 builtin to call a parent class.
=> Use Python 3 super()

.travis.yml, setup.cfg, tox.ini
PyPy has been officially supported by 2.0.
=> Document and test support for PyPy

tests/test_filter.py
=> Add tests for ImportableModuleFilter._skip()

.travis.yml, integration_tests/build_django.py
We seem to break the Django build, so let's use it as a way to detect
breaking changes in our implementation.
=> add integration test for django documentation build

.gitignore, docs/source/customize.rst, sphinxcontrib/spelling/__init__.py, sphinxcontrib/spelling/builder.py
=> add a verbose parameter

README
Add the second 'i' to sphinxcontrib
=> Spelling edit in README

docs/source/history.rst, sphinxcontrib/spelling/builder.py, sphinxcontrib/spelling/checker.py, sphinxcontrib/spelling/directive.py, sphinxcontrib/spelling/filters.py, tests/test_builder.py
Just a little code cleanup, mostly around using f-strings over concatenation and using lazy evaluation for logging. Outside of string interpolation, there was an unused import, a couple unneeded return statements, and redefinition of a built-in (filter).
=> Minor code tweaks

docs/source/index.rst, tox.ini
=> docs: add linkcheck to build

tests/test_builder.py
Add a test for the fix to #167
=> builder: add test for docstring fix

.github/workflows/check.yml, .mergify.yml, tests/helpers.py, tests/test_builder.py, tests/test_filter.py, tox.ini
=> ensure tests work without git history

docs/source/history.rst, sphinxcontrib/spelling/directive.py, tox.ini
=> quiet debug printing

docs/source/customize.rst, docs/source/history.rst
Acked-by: Doug Hellmann <doug@doughellmann.com>
=> update documentation for spelling:ignore role

docs/source/developers.rst, docs/source/spelling_wordlist.txt
This is documented in tox.ini, too.
=> add docs for setting up enchant library

docs/source/history.rst, pyproject.toml, sphinxcontrib/spelling/filters.py, tests/test_filter.py
=> use json api to retrieve names from pypi.org
