sphinx-contrib/spelling

nosetest.cfg
sphinxcontrib/spelling/builder.py

There's value in not always failing on a spelling - for example, if you want to use the tool merely as a guideline rather than a strict check. We could add a spelling-specific option to make failures optional, but we already have a similar option available - Sphinx's `warning-is-error` option. Stop setting the builder status and instead emit a warning on build failures.

Use warning is error

---

sphinxcontrib/spelling/checker.py

Discovered by @p1otr during a review of sphinxcontrib-spelling Debian
package.

Don't use mutable default argument

---

docs/source/customize.rst

Hello, 
first of all thanks for the great work with this extension 😄 👍 
I was working with the extension and someone suggested on a PR I have done in Pandas that perhaps we should divide the wordlist in two (one for terms, one for names). I checked the documentation but there was no mention of this possibility, then checked the code and saw that this was possible.
This PR is just intended to add this to documentation, I'm not sure if the place I choose to add it is the right one, please let me know what you think and if you would like me to change anything 👍

Mention how to create multiple wordfiles

---

.gitignore
sphinxcontrib/spelling/builder.py

Hello,
this might be a silly PR (and pretty small one) but I have encountered an issue when working on a PR to pandas.
Basically, I have a script that updates a custom wordlist with contributors names, but if the file is empty and I run the spelling check, then an exception is thrown `IndexError` since the check on line 116 assumes that the file is not empty.
Of course, there is a work around this, but perhaps this could be useful to people that would like to have an empty file and then update it in the future.

Allow custom empty files

---

sphinxcontrib/spelling/builder.py

The `warning()`s alias `warn()` was never intended to be public, and
is deprecated since forever. See https://bugs.python.org/issue13235

Logging: use `warning()` instead of its deprecated alias

---

setup.cfg
setup.py

Since sphinx >= 2 dropped Python 2.7 support, this package also does.
Remove Trove 2.7 classifier and 2.7 bug workaround.

No Python 2.7 support anymore.

---

docs/source/customize.rst
sphinxcontrib/spelling/builder.py

Allow the spelling_filters config option to contain strings that refer
to the classes instead of using the classes directly. This avoids
invalidating the config hash every time the config module is loaded,
which speeds up subsequent documentation builds because every file is
not processed every time.
Addresses #39

allow customizing with classes using import strings

---

docs/source/conf.py
docs/source/customize.rst
sphinxcontrib/spelling/__init__.py
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/checker.py
sphinxcontrib/spelling/tests/test_checker.py

This adds a boolean `spelling_show_whole_line` option that includes the whole
line (the substring from the previous \n to the next \n) in the output for each
misspelling. This makes it easier to understand and locate misspellings in large
products.
The output from the example in #43 is now:
```
index.rst:1:xyz::different text xyz other text                                                                                                                                                                  
index.rst:1:xyz::some words xyz more words
```
which is much easier to locate, despite the file name and line numbers not being perfect.
Fixes #43

Add an option to show the line containing a misspelling for context

---

docs/source/run.rst

Without `-W`, sphinx-build will not return an error code and make will succeed. 
Closes #52

Add -W arg to sphinx-build so warnings cause error

---

sphinxcontrib/spelling/__init__.py

This is for issue #34, so that parallel builds fail with the appropriate error message.

Mark as unsafe for parallel builds

---

docs/source/customize.rst
sphinxcontrib/spelling/__init__.py
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/tests/test_builder.py

This PR addresses #3 by adding a configuration option to provide a list of files which should be ignored and not spell-checked. There is a test case which verifies functionality and documentation for the new option has been added.

Ignore files 

---

setup.cfg

Hi,
It looks like this isn't used any more since you switched to pytest.

Remove unused fixtures dependency

---

sphinxcontrib/spelling/checker.py

Fixes warnings during tests:
.../spelling/sphinxcontrib/spelling/checker.py:34: DeprecationWarning: passing 'filters' as a non-keyword argument to get_tokenizer() is deprecated
Tracks upstream change:
https://github.com/pyenchant/pyenchant/commit/36930b55ac9881445a262a355af74c83ceef28e1

Pass 'filters' as a keyword argument to pyenchant get_tokenizer()

---

setup.cfg

The packages is Python 3 only (no Python 2) so document as such.
Include the classifier "Programming Language :: Python :: 3" for
automated tools.

Add missing trove classifiers for Python-3-only support

---

setup.cfg

Some big name projects, such as Django, have been using
sphinxcontrib-spelling for a very long time, suggesting it has reached a
more mature status than "beta".

Document the project as stable and ready for production use

---

sphinxcontrib/spelling/filters.py

Fixes warning when running the tests:
spelling/sphinxcontrib/spelling/filters.py:11: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Per the docs, use importlib.util.find_spec() instead of
imp.find_module(). See:
https://docs.python.org/3/library/imp.html#imp.find_module
For details on importlib.util.find_spec(), see:
https://docs.python.org/3/library/importlib.html#importlib.util.find_spec

Replace deprecated imp module with importlib

---

docs/source/conf.py
sphinxcontrib/__init__.py
sphinxcontrib/spelling/asset.py
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/checker.py
sphinxcontrib/spelling/directive.py
sphinxcontrib/spelling/filters.py
tests/test_builder.py
tests/test_checker.py
tests/test_filter.py

pyupgrade is a tool to automatically upgrade syntax for newer versions
of the Python language. For details, see:
https://github.com/asottile/pyupgrade
As the project is Python 3 only, this tools applies several
simplifications:
- No longer need to specify Python file encoding. Python files are read
as utf-8 by default.
- No longer need to prefix Unicode strings with u. Python 3 strings are
Unicode by default.
- No longer need to use io.open() as the builtin open() supports all
features.
- Use set literals and set comprehension.
- No longer need to inherit from object as Python 3 removed the legacy
old-style classes.

Run pyupgrade across the codebase

---

docs/source/history.rst
sphinxcontrib/spelling/__init__.py

These words are both proper nouns.

Capitalize "Python" and "Sphinx" in docs and comments

---

setup.cfg
tox.ini

Remove `usedevelop = True`. It is better to test the installed package
than an in-place one. Testing against the installed version is more
robust, representative, and catches some packaging issues.
Replace `deps = .[test]` with tox's builtin `extras` configuration
option. For details on this features, see:
https://tox.readthedocs.io/en/latest/config.html#conf-extras.
Use `skip_install = true` for the linter environment. Installing
sphinxcontrib-spelling to a virtual environment is unnecessary for
flake8 purposes. This saves a small amount of time when running tox as
there are fewer operations to perform. For details on this features,
see: https://tox.readthedocs.io/en/latest/config.html#conf-skip_install.
As the package installation no longer occurs, using the extras won't
apply so the …

Simplify and improve tox configuration

---

docs/source/history.rst
setup.cfg
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/filters.py

Python 3.5 has been end-of-life since 2020-09-30.
See https://devguide.python.org/devcycle/#end-of-life-branches for a
full list of end-of-life Pythons.
Removing support for end-of-life Python allows for better adoption of
new Python features (such as f-strings and type hinting) and reduces the
project's testing and maintenance resources.
Using pypinfo, we can see Python 3.5 made up only a small percentage of
real life usage over the last month:
$ pypinfo -md -pc sphinxcontrib-spelling pyversion
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.7            |  39.60% |         37,528 |
| 2.7            |  34.30% |         32,506 |
| 3.8            |  14.14% |         13,396 |
| 3.6            |  11.26% |         10,675 |
| 3.5            | …

Remove support for end-of-life Python 3.5

---

sphinxcontrib/spelling/filters.py

For Python 3, all attributes are Unicode strings. There is no encoding
done which was necessary for Python 2 to handle byte strings.

Remove unnecessary UnicodeEncodeError (due to Python 3)

---

sphinxcontrib/spelling/__init__.py

The comment assert that "app" will be a module when running tests.
However, through experimentation, this doesn't appear to be the case.
Simplify as well as unify the function's return type.

Remove obsolete comment and guard in setup()

---

sphinxcontrib/spelling/filters.py

Reported issue: https://github.com/sphinx-contrib/spelling/issues/96
In 6.0.0, `importlib.util.find_spec` was introduced as a replacement to `imp.find_module`.
However, there is a scenario where it can raise `ValueError` (new behaviour to this codebase):
https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
This PR attempts to handle this scenario.
P.S. I could not find related test to this logic. I'd be happy to write one (and will try now), but I think, I'd need some assistance here. Any pointers?
Best,
Rust

Handle `ValueError` raised by `importlib.util.find_spec`

---

docs/source/conf.py
docs/source/developers.rst
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/filters.py
tests/test_builder.py
tox.ini

isort is a command line tool to automate formatting of Python imports.
It makes all imports formatted in a consistent way.
This simplifies the contributor process by removing the need to think
about parts of the project's preferred coding style.

Introduce isort for automated formatting of Python imports

---

tests/test_builder.py

Since Python 3, the builtin open() supports all features provided by
codecs.open() (much like io.open()). Its use is no longer required.

Replace codecs.open() with Python 3 builtin open()

---

.gitignore
.travis.yml
docs/source/developers.rst

Use of reno was removed in ba98010ef25573e1aa3a64ac7f91e039ab38ba9d.

Remove remaining references to reno release notes manager

---

tests/test_filter.py

Using pytest.mark.parametrize() allows each test case to run
independently. In the event of a test failure, the other parameters will
still run as separate tests.

Parametrize test_contributors

---

tox.ini

Make it easier to test all supported Pythons to help ensure changes
don't introduce incompatibilities.

Include all supported Pythons in the tox test matrix

---

docs/source/history.rst

Was released on Oct 19, 2020.
https://pypi.org/project/sphinxcontrib-spelling/7.0.0/#history

Update history.rst with 7.0.0 release

---

sphinxcontrib/spelling/filters.py
tests/test_filter.py

This reverts commit db8d0b3a14de97ac9ecc571f75c1bc2991455b07.
Using importlib.find_spec() is not safe at runtime as it can import
modules which will cause side effects within environments.
From the docs:
https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
> If name is for a submodule (contains a dot), the parent module is
> automatically imported.
This has caused issues in some projects, including python-ldap which
includes the word "setup.cfg" causing its "setup.py" file to be imported
which eventually raises a SystemExit error. A test was written to catch
this case.
A deprecation warning is preferable over system level side effects.

Revert "Replace deprecated imp module with importlib"

---

.github/workflows/python-publish.yaml

See
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

update publish action based on python.org instructions

---

.github/workflows/python-publish.yaml

We need the history to get the version number.

clone the whole repo when building release

---

.github/workflows/python-publish.yaml

Don't run an action that is likely to fail on a fork of the repo.

do not run the build-n-publish job on forks of the repo

---

docs/source/customize.rst
sphinxcontrib/spelling/__init__.py
sphinxcontrib/spelling/builder.py

Resolves #108 
Adds a config option:  spelling_warning that will emit misspellings as sphinx warning instead of info message. The sphinx warning format is better suited for IDE's that no how to parse error/warnings and automatically navigate to the file/line. Also, you can invoke sphinx with -q and still see warnings.

add spelling_warning configuration option

---

setup.cfg

* Move `python_requires` to `[options]` section, where it belongs: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
* Use underscores for keys rather than dashes; dashes happen to work but are not documented: https://github.com/asottile/setup-cfg-fmt#normalizes-dashes-to-underscores-in-keys

Correct setup.cfg

---

sphinxcontrib/spelling/filters.py
tests/test_filter.py

* Add ``sys.builtin_module_names`` to the initial sets, to skip running ``imp.find_module`` for these names which we know will succeed.
* Check that the given name is a valid module name with a cheap string check, before trying to run the more expensive ``imp.find_module()``.
* Close the file returned by ``imp.find_module()`` to avoid this resource warning:
```
/.../site-packages/sphinxcontrib/spelling/filters.py:187: ResourceWarning: unclosed file <_io.TextIOWrapper name='/.../site-packages/decorator.py' mode='r' encoding='utf-8'>
imp.find_module(word)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Improve ImportableModuleFilter

---

sphinxcontrib/spelling/filters.py
tox.ini

The imp module is deprecated, so replace it with calls to importlib.
Addresses #124

filters: do not use imp in ImportableModuleFilter

---

.github/workflows/history-update.yaml
.mergify.yml

There's no need to run the check if we push a tag reference.

history-update: do not run check if ref is a tag

---

docs/source/history.rst
sphinxcontrib/spelling/filters.py

If the test suite is invoked by running `python -m pytest` instead of
`pytest` then there will be no `__main__` and find_spec() will fail.
Fixes #141

filters: treat __main__ as special

---

docs/source/history.rst
sphinxcontrib/spelling/filters.py
tox.ini

If the word looks like a python module filename, strip the extension to
avoid the side-effect of actually importing the module. This prevents, for
example, 'setup.py' triggering an import of the setup module during a doc
build, which makes it look like Sphinx is complaining about a commandline
argument.
Fixes #142

filters: fix python filename handling

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py

If the extra word list is empty an IndexError is thrown. Prevent the
error by checking the contents of the file before using the list.

handle empty word list

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py

Ensure the correct filename is reported as the location of a
misspelled word when the word is in an included file.
Fixes #153

builder: show the correct filename for included files

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/checker.py
tests/test_checker.py

Use the line of the misspelled word as source position in message

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py

Previous commits included the offset in the log message, this updates
the data saved to the output .spelling file to include the same value.
Fixes #159

builder: include the line offset in location saved to output file

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py

Do not crash when reporting bad spelling in docstrings

---

.mergify.yml

This can be restored when https://code.djangoproject.com/ticket/33753
is fixed.

ci: do not require django ci job

---

docs/source/customize.rst
docs/source/history.rst
sphinxcontrib/spelling/__init__.py
sphinxcontrib/spelling/builder.py
tests/test_builder.py

Allow the user to control the number of suggestions displayed in the
output through a configuration option.
Closes #151

feature: limit the suggestions shown in the output

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py
tests/test_builder.py

Include captions in the list of special text node types the builder
processes.
Fixes #36

builder: check text of captions

---

docs/source/customize.rst
docs/source/history.rst
sphinxcontrib/spelling/builder.py
tests/test_builder.py

Add tests for previous work to support multiple wordlist filenames.
Clean up documentation for the configuration option.
Refactor wordlist filename handling in the builder to make it more
testable.
Fixes #169

builder: add tests for multiple wordlist filenames

---

docs/source/history.rst
sphinxcontrib/spelling/filters.py
tests/test_filter.py
tox.ini

Fix the ImportableModuleFilter so that when importing a module results in a
SystemExit being raised we trap the exit and treat it as an issue finding
the module.
Fixes #180

filters: trap exits from imported modules

---

docs/source/history.rst
sphinxcontrib/spelling/domain.py
sphinxcontrib/spelling/role.py
tests/test_builder.py

A line like:
> This :spelling:word\`foobared\` role needs to be fixed.
would be rendered in the output exactly like that, instead of what it should be:
> This foobared role needs to be fixed.
Turns out the cause is quite simple: the nodes.Text object from docutils does not hold both the raw text and the "real" text, so it is being passed the raw text, which includes the role name as we see it.
Add a test case to cover this as well.
**NOTE**: The other (shorter) way to fix this is simply to change this line:
https://github.com/sphinx-contrib/spelling/blob/f4a419ed6341ba929c0007e82eb1652d9ee60d38/sphinxcontrib/spelling/role.py#L16
to
```python
return super().__call__(role, text, text, lineno, inliner, 
```
But I think that is more hacky. If you disagree, I can edit this commit.
Fixes #188

Fix spelling:word role rendering verbatim

---

.github/workflows/check.yml
.github/workflows/history-update.yaml
.github/workflows/integration.yaml
.github/workflows/python-publish.yaml
.github/workflows/test.yml

Actions using older versions of node are
deprecated. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

github: update checkout action to v3

---

setup.cfg

Fix the following setuptools deprecation warning:
> Usage of dash-separated 'description-file' will not be supported
> in future versions. Please use the underscore name 'description_file'
> instead

Update setup.cfg to use description_file

---

docs/source/history.rst
sphinxcontrib/spelling/builder.py
sphinxcontrib/spelling/domain.py
sphinxcontrib/spelling/role.py
tests/test_builder.py

This is an attempt to add a `:spelling:ignore:` role that allows a particular word, or phrase, to be ignored by the spelling checker _but only in this location_.
It does not add the word to the list of good words.  Any other occurrences of the word elsewhere _will_ be flagged as spelling errors. (Unless it _is_ actually spelt correctly of course).
This fixes #198.

Add a spelling ignore role

---

.github/workflows/check.yml
.github/workflows/integration.yaml
.github/workflows/python-publish.yaml

Build and publish Python distributions to PyPI Node.js 12 actions are
deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please
update the following actions to use Node.js 16: actions/setup-python,
actions/setup-python

update github action to latest

---

sphinxcontrib/spelling/builder.py
tests/test_builder.py

Add a test showing that the `only` directive works for ignoring sections of
content that has content that should not be checked.
Addresses #204

add test showing that only directive works for ignoring blocks

---

docs/source/history.rst
sphinxcontrib/spelling/filters.py

The following error occurs in `_get_contributors()` if git is not installed.
> FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
Treat this the same as if `git` fails, catch the error and print a warning.

gracefully handle if git is not installed
